### ISSUE TITLE
update indentation style

### ISSUE THREAD

**Issue by donghwan-shin** [SepShr/MLCSHE#10]
https://github.com/SepShr/MLCSHE/blob/cc5018836483c45b498e35d8bc4eff32a81e194f/tests/test_breedScenario.py#L7

In this example, a better way of indentation for multi-line code is:
```python
        p = [
            creator.Scenario([1, 2.0, False]), 
            creator.Scenario([8, 3.5, True]),
            creator.Scenario([70])
        ]
```

**Comment by SepShr** [comment]
All indentations updated.
