### ISSUE TITLE
In progress?

### ISSUE THREAD

**Issue by donghwan-shin** [SepShr/MLCSHE#14]
https://github.com/SepShr/MLCSHE/blob/cc5018836483c45b498e35d8bc4eff32a81e194f/CCEA.py#L856

I assume that you will add some comments and/or update the variable names to be more understandable? 😉

**Comment by SepShr** [comment]
Sure! it is still in progress.

**Comment by SepShr** [comment]
The variables are renamed and relevant comments are added.
