### ISSUE TITLE
install error (python requirements)

### ISSUE THREAD

**Issue by donghwan-shin** [SepShr/MLCSHE#29]
On an Amazon EC2 instance, when I tried to install python package requirements using:
```
(venv) pip install -r requirements.txt
```

I got the following error:
```
ERROR: Could not find a version that satisfies the requirement pywin32==301 (from -r requirements.txt (line 37)) (from versions: none)
ERROR: No matching distribution found for pywin32==301 (from -r requirements.txt (line 37))
```

FYI, the cloud instance has Python 3.8.10 and pip 20.0.2 from /home/ubuntu/MLCSHE/venv/lib/python3.8/site-packages/pip (python 3.8)

**Comment by SepShr** [comment]
Commit `c40df31f0ca76ecc55b7536efe32230ea6b9af65` fixes the issue.
