### ISSUE TITLE
Implement parallelization V.1, i.e., 2-3 docker simulations at the same time.

### ISSUE THREAD

**Issue by SepShr** [SepShr/MLCSHE#39]
A simple parallel simulation job manager has to be implemented that allows for simulation jobs to be added to the queue, and assign them to a known pool of workers (simulators).

**Comment by SepShr** [comment]
The parallelization has been implemented and works for a small number of evaluations. However, when running a longer search with population sizes of 10, the code raises the following exception:

```bash
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/home/sepehr/AV/MLCSHE/MLCSHE/simulation_manager_cluster.py", line 112, in _process_sim_job
    self.get_results(container, simulation_log_file_name,
  File "/home/sepehr/AV/MLCSHE/MLCSHE/simulation_manager_cluster.py", line 413, in get_results
    self.copy_to_host(container, file_name, source_path, destination_path)
  File "/home/sepehr/AV/MLCSHE/MLCSHE/simulation_manager_cluster.py", line 444, in copy_to_host
    pw_tar.extractall(dst_file_path)
  File "/usr/lib/python3.8/tarfile.py", line 2028, in extractall
    self.extract(tarinfo, path, set_attrs=not tarinfo.isdir(),
  File "/usr/lib/python3.8/tarfile.py", line 2069, in extract
    self._extract_member(tarinfo, os.path.join(path, tarinfo.name),
  File "/usr/lib/python3.8/tarfile.py", line 2141, in _extract_member
    self.makefile(tarinfo, targetpath)
  File "/usr/lib/python3.8/tarfile.py", line 2190, in makefile
    copyfileobj(source, target, tarinfo.size, ReadError, bufsize)
  File "/usr/lib/python3.8/tarfile.py", line 249, in copyfileobj
    raise exception("unexpected end of data")
tarfile.ReadError: unexpected end of data
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "run_iccea.py", line 89, in <module>
    main()
  File "run_iccea.py", line 79, in main
    solution = solver.solve(
  File "/home/sepehr/AV/MLCSHE/MLCSHE/src/main/ICCEA.py", line 138, in solve
    cs_archive_gen, popScen, popMLCO = self.evaluate(
  File "/home/sepehr/AV/MLCSHE/MLCSHE/src/main/ICCEA.py", line 389, in evaluate
    cs_list_per_gen = self.evaluate_joint_fitness(complete_solutions_set)
  File "/home/sepehr/AV/MLCSHE/MLCSHE/src/main/ICCEA.py", line 308, in evaluate_joint_fitness
    self.num_sim, results = self.toolbox.compute_safety_cs_list(
  File "/home/sepehr/AV/MLCSHE/MLCSHE/problem.py", line 60, in compute_safety_value_cs_list
    results = start_computation(simulator)
  File "/home/sepehr/AV/MLCSHE/MLCSHE/simulation_manager_cluster.py", line 458, in start_computation
    results = [list(f.result()) for f in futures]
  File "/home/sepehr/AV/MLCSHE/MLCSHE/simulation_manager_cluster.py", line 458, in <listcomp>
    results = [list(f.result()) for f in futures]
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
tarfile.ReadError: unexpected end of data
```
The log file and the console output of the run are below:
[20220717_150908_CCEA.log](https://github.com/SepShr/MLCSHE/files/9243489/20220717_150908_CCEA.log)

[typescript.log](https://github.com/SepShr/MLCSHE/files/9243495/typescript.log)

Note that I have repeated the experiment twice and it still raises the same exception at the exact same time.

**Comment by donghwan-shin** [comment]
@SepShr May I ask what `tar` file we are reading above? I don't understand why we have an error `tarfile.ReadError: unexpected end of data`...

**Comment by donghwan-shin** [comment]
I don't know what tar files are used, but the error could be because of trying to read/access a tar file before the writing/generating of the file is completed. Or, different processes/threads try to read/write on the same tar file. Can you check if this would be the case?

**Comment by SepShr** [comment]
Apologies for the incomplete explanation. So, docker-py only has methods to communicate `tar` files between the host and the container using `put_archive()` and `get_archive()`. Thus, the simulation results and the `finished.txt` file and communicated as a `tar` file.

**Comment by SepShr** [comment]
So, the tarfiles are not shared between processes as far as I know. Also, the code transfers the results after the container is stopped. However, I have to make sure that whether the process is blocked until the container is stopped or not. If not, it might be the case that it is trying to copy a file before it is fully available. However, it is still weird that this only happens at a certain point repeatedly.

**Comment by donghwan-shin** [comment]
Does it happen at a certain point repeatedly? If so, it could be that a *problematic* tar file (including an irregular character/byte) is generated at that certain point, possibly related to a compatibility/encoding issue. Can you have the last tar file when the error occurs? Is it readable through `get_archive()` if you access it independently?

**Comment by SepShr** [comment]
It has happened at the same point twice. All tar files are extracted using the function `copy_to_host()` in `simulation_manager_cluster.py`. The thing is, I am not even sure during which process it was trying to copy the results, since all the processes had just ended and the results were successfully recorded.

**Comment by SepShr** [comment]
Hi,
So, I profiled the memory consumption of the algorithm using `mprof` and the findings are as follows:
Our current version, receives a batch of jobs, runs them using a `ProcessPoolExecutor` and returns all the simulation results at the end. Basically:
```python
def start_computation(sim_manager, max_workers: int = cfg.max_workers):
"""Runs the simulation jobs in parallel and returns the results.
"""
    with concurrent.futures.ProcessPoolExecutor(max_workers=max_workers) as executor:
        futures = {executor.submit(sim_manager._process_sim_job, sim_job): sim_job
                   for sim_job in sim_manager.job_list}
        logger.info('jobs submitted')
        for future in concurrent.futures.as_completed(futures):
            logger.info(f'Run {futures[future]} did finish')
        results = [list(f.result()) for f in futures]
        del futures
        sim_manager.job_list.clear()
        gc.collect()
    return results
```
For this version, the memory profile is provided below:
![memory_profile](https://user-images.githubusercontent.com/57507176/183301664-e9e93426-826b-468a-a3ca-75d10738f173.png)

As shown in the figure, memory consumption is almost steady except for the peaks that increase over time.

Another alternative is to split the inputs into batches and submit and run the simulation to a new `ProcessPoolExecutor` for each batch. Interestingly, as shown in the figure below, this is worse and the average memory consumption increases multiple fold.
![memory_profile](https://user-images.githubusercontent.com/57507176/183301887-c80e0e4e-dec8-43fe-9c4d-3821d45f8e6e.png)

There is another alternative where you keep the same `ProcessPoolExecutor` and submit jobs in batches. I will try that as well and provide report the results.

**Comment by donghwan-shin** [comment]
The following code works well on my local machine, without any error:

```python
import docker
import tarfile
from io import BytesIO
from datetime import datetime

# initialize docker container
client = docker.from_env()
container = client.containers.run(
    image="donghwan/docker-python-copy-test:v1",  # a test docker image
    detach=True,
)

# copy files to host
files = [  # two files in the docker container
    '/working/20220809_145238_sim_pylot_1.log_ex.log',
    '/working/finish.txt'
]
timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
for f in files:
    ret, stat = container.get_archive(f)
    filelike = BytesIO(b"".join(b for b in ret))
    with tarfile.open(fileobj=filelike) as tar:
        tar.extractall(f'./results_{timestamp}')

# remove container
container.remove()

```

I didn't use `Mount` and it still works. I am not sure if we really need it in this case.
