### ISSUE TITLE
issue in post-processing

### ISSUE THREAD

**Issue by donghwan-shin** [SepShr/MLCSHE#43]
I found the following code from https://github.com/SepShr/MLCSHE/blob/Dev-Sepehr/pylot/postprocess.ipynb.

```python
def remove_similar(cs_archive: list, min_distance: 0.0) -> list:
    """Remove similar complete solutions from `cs_archive` based on
    their pairwise distance.
    """
    # Compute pairwise distance between all complete solutions solutions.
    pdist = PairwiseDistance(
        cs_archive, cfg.numeric_ranges, cfg.categorical_indices)

    # Remove solutions with pairwise distance lower than `min_distance`
    if len(cs_archive) > 1:
        cs_archive_distinct = [cs_archive[0]]
        for candidate in cs_archive:
            for member in cs_archive_distinct:
                if pdist.get_distance(candidate, member) >= min_distance:
                    cs_archive_distinct.append(candidate)
                    break
    else:
        cs_archive_distinct = cs_archive

    return cs_archive_distinct
```

Here, a `candidate` in `cs_archive` is added to `cs_archive_distinct` if there is **_at least one_** `member` in `cs_archive_distinct` such that the distance between `candidate` and `member` is greater than or equal to `min_distance`. Is this what we want? 

According to my understanding, we wanted to add `candidate` into `cs_archive_distinct` if the distance between `candidate` and `member` is greater than or equal to `min_distance` for **_all_** `member`s currently in `cs_archive_distinct`. What do you think? Maybe I forgot or misunderstood something...

**Comment by SepShr** [comment]
Does the following snippet, do what you mentioned in the second paragraph?

> According to my understanding, we wanted to add `candidate` into `cs_archive_distinct` if the distance between `candidate` and `member` is greater than or equal to `min_distance` for all members currently in `cs_archive_distinct`. 

```python
def remove_similar(cs_archive: list, min_distance: 0.0) -> list:
    """Remove similar complete solutions from `cs_archive` based on
    their pairwise distance.
    """
    # Compute pairwise distance between all complete solutions solutions.
    pdist = PairwiseDistance(
        cs_archive, cfg.numeric_ranges, cfg.categorical_indices)

    # If a member of the cs_archive is not similar to any other member in the cs_archive_distinct
    # list, then add it to the cs_archive_distinct list.
    cs_archive_distinct = []
    if len(cs_archive) > 1:
        for cs in cs_archive:
            if not any([pdist.get_distance(cs, cs_distinct) < min_distance for cs_distinct in cs_archive_distinct]):
                cs_archive_distinct.append(cs)
    else:
        cs_archive_distinct = cs_archive
    

    return cs_archive_distinct
```

**Comment by SepShr** [comment]
Commit 3ce1451125457177681f957e8ce17a21b29ac739 solves this issue
