### ISSUE TITLE
normalization issue in measure_heom_distance()

### ISSUE THREAD

**Issue by donghwan-shin** [SepShr/MLCSHE#8]
In the following function:
https://github.com/SepShr/MLCSHE/blob/cc5018836483c45b498e35d8bc4eff32a81e194f/CCEA.py#L594

I wonder if it's okay to normalize the data inside the function.
For example, the value of 1 can be normalized to 0.1 when `X` has the maximum value of 10 but 0.5 when `X` has the maximum value of 2. 

This is not an issue if the calculated normalized distance is not compared to those from other `X`s. Is this the case?

**Comment by SepShr** [comment]
Issue acb74e86d0d79cf4d14e3f4f03a90557783362e3 addresses solves this issue by using absolute range of numeric values not the range available from data.
